name: Dani A. Ona
author: Dani Antonio Ona
baseurl: ""
description: A Filipino Geek. Developer
github: http://www.github.com/zxcdani
twitter: http://www.twitter.com/dandansoysauce
facebook: http://www.facebook.com
linkedin: https://ph.linkedin.com/in/daniona
email: ona.dani.a@gmail.com
location: Davao City
disqus: apinoygeek

##Make sure to edit the above fields, especially for disqus.

highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
